apiVersion: v1
kind: ConfigMap
metadata:
  name: ueba-platform-config
  namespace: ueba-saas
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka.ueba-saas.svc.cluster.local:9092"
  ELASTICSEARCH_URL: "http://elasticsearch.ueba-saas.svc.cluster.local:9200"
  MLFLOW_TRACKING_URI: "http://mlflow.ueba-saas.svc.cluster.local:5000"
  DEFAULT_REGION: "us-east-1"
  SESSION_SECURE_COOKIE: "true"
  CORS_ORIGINS: "https://app.ueba-saas.com"

