apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ueba-platform-ingress
  namespace: ueba-saas
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: ueba-saas
spec:
  rules:
    - host: app.ueba-saas.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80

