apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ueba-platform-secrets
  namespace: ueba-saas
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ueba-platform-secrets
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: /ueba/prod/app
        property: jwt_secret
    - secretKey: DATABASE_URL
      remoteRef:
        key: /ueba/prod/app
        property: database_url
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: /ueba/prod/app
        property: google_client_id
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: /ueba/prod/app
        property: google_client_secret

